# Generated by Django 3.2.5 on 2021-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0006_jeffersonbuildingdatafsh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.AddField(
            model_name='contact',
            name='detail',
            field=models.TextField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='detailmethodse1',
            field=models.TextField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='locationproblem',
            field=models.TextField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject1',
            field=models.TextField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject2',
            field=models.TextField(default='SOME STRING', max_length=60),
        ),
    ]
