# Generated by Django 3.2.5 on 2021-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0007_auto_20210830_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='detailmethodse2',
            field=models.TextField(default='SOME STRING', max_length=200),
        ),
    ]
