# Generated by Django 3.2.5 on 2021-10-20 23:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0010_contact_selecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeffersonAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADDRESS', models.CharField(max_length=10, null=True)),
                ('STREET', models.CharField(max_length=25, null=True)),
                ('SUITE', models.CharField(max_length=10, null=True)),
                ('ZIP', models.CharField(max_length=10, null=True)),
                ('AREA_NAME', models.CharField(max_length=30, null=True)),
                ('STREET_NAM', models.CharField(max_length=43, null=True)),
                ('ST_TYPE', models.CharField(max_length=5, null=True)),
                ('WO_AREA', models.CharField(max_length=30, null=True)),
                ('a_Slope', models.FloatField()),
                ('u_Intercep', models.FloatField()),
                ('FD100Year', models.FloatField()),
                ('FD500Year', models.FloatField()),
                ('FLD_ZONE', models.CharField(max_length=17, null=True)),
                ('BFE', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('WSF1', models.FloatField()),
                ('WSF2', models.FloatField()),
                ('mpoint', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='jeffersonbuildingdatafsh',
            name='FID_1',
            field=models.BigIntegerField(default=' '),
        ),
    ]
