# Generated by Django 3.2.5 on 2021-10-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0011_auto_20211020_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeffersonaddress',
            name='ADDRESS',
            field=models.CharField(default=' ', max_length=10, null=True),
        ),
    ]
